apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    networking.gke.io/managed-certificates: wordpress-managed-cert  # Name of your ManagedCertificate resource
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 80
    protocol: TCP
  selector:
    app: wordpress
